name: Workflow

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  windows:
    name: windows-2022
    runs-on: windows-2022
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Nuke build
        run: ./.nuke/build.cmd Compile PublishGitHub --GitHubToken ${{ secrets.MY_PERSONAL_TOKEN }}

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
      - name: Bump version and commit
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
        run: |
          git add version.txt
          git commit -m 'Bump version'
          git push

